/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useTexture } from '@react-three/drei'

export function King(props) {
    const { nodes, materials } = useGLTF('/chessking.glb')
    
    const bakedTexture = useTexture("/chessjpg.jpg");

	bakedTexture.flipY = false;
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.king001_Baked.geometry}
        material={nodes.king001_Baked.material}
        position={[1.376, 1.869, 1.072]}
        scale={1.093}
      ><meshBasicMaterial map={bakedTexture} /></mesh>
    </group>
  )
}

useGLTF.preload('/chessking.glb')


