/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Chess2(props) {
  const { nodes, materials } = useGLTF('/chess-v2.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Siena_Table_Baked.geometry}
        material={materials.MergedBake_Baked}
        position={[1.047, 0.578, 1.244]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[1.229, 1.47, 1.229]}
      />
    </group>
  )
}

useGLTF.preload('/chess-v2.glb')