/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useTexture } from '@react-three/drei'

export function Chess4(props) {
    const { nodes, materials } = useGLTF('/chessmatnelkul2.glb')
    
      const bakedTexture = useTexture("/asd.jpg");

	bakedTexture.flipY = false;
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Siena_Table_Baked.geometry}
        material={nodes.Siena_Table_Baked.material}
        position={[1.047, 0.578, 1.244]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[1.229, 1.47, 1.229]}
      ><meshBasicMaterial map={bakedTexture} /></mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.board_Baked.geometry}
        material={nodes.board_Baked.material}
        position={[1.072, 1.617, 1.246]}
        scale={1.093}
      ><meshBasicMaterial map={bakedTexture} /></mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Light_Desk_Baked.geometry}
        material={nodes.Light_Desk_Baked.material}
        position={[0.488, 1.623, 1.26]}
        rotation={[-Math.PI / 2, 0, 0.976]}
        scale={100}
      ><meshBasicMaterial map={bakedTexture} /></mesh>
    </group>
  )
}

useGLTF.preload('/chessmatnelkul2.glb')

