/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Chess(props) {
  const { nodes, materials } = useGLTF('/chess.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Siena_Table_Baked.geometry}
        material={materials.MergedBake_Baked}
        position={[1.047, 0.578, 1.244]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[1.229, 1.47, 1.229]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.RUYLOPEZPAWNWHITE_Baked.geometry}
        material={materials.MergedBake_Baked}
        position={[1.129, 1.711, 1.195]}
        scale={1.093}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.RUYLOPEZPAWNBLACK_Baked.geometry}
        material={materials.MergedBake_Baked}
        position={[1.014, 1.711, 1.189]}
        scale={1.093}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Knight003_Baked.geometry}
        material={materials.MergedBake_Baked}
        position={[1.127, 1.724, 1.287]}
        scale={1.093}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Knight002_Baked.geometry}
        material={materials.MergedBake_Baked}
        position={[1.358, 1.724, 1.101]}
        scale={1.093}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.king001_Baked.geometry}
        material={materials.MergedBake_Baked}
        position={[1.247, 1.869, 1.072]}
        scale={1.093}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.king000_Baked.geometry}
        material={materials.MergedBake_Baked}
        position={[1.01, 1.869, 1.419]}
        scale={1.093}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.board_Baked.geometry}
        material={materials.MergedBake_Baked}
        position={[1.072, 1.617, 1.246]}
        scale={1.093}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Light_Desk_Baked.geometry}
        material={materials.MergedBake_Baked}
        position={[0.488, 1.623, 1.26]}
        rotation={[-Math.PI / 2, 0, 0.976]}
        scale={100}
      />
    </group>
  )
}

useGLTF.preload('/chess.glb')
